apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: n-a-a-vre-im-zhuyh-gmail-com-
  labels:
    vlab_slug: n-a-a-vre
spec:
    entrypoint: n-a-a-vre-im-zhuyh-gmail-com
    serviceAccountName: executor
    volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes: [ "ReadWriteMany" ]
        persistentVolumeReclaimPolicy: Delete
        resources:
          requests:
            storage: 1Gi
    arguments:
      parameters:
    templates:
    - name: n-a-a-vre-im-zhuyh-gmail-com
      dag:
        tasks:
        - name: visualize-api-im-zhuyh-gmail-com-91f4b9d
          template: visualize-api-im-zhuyh-gmail-com-91f4b9d-tmp
    - name: visualize-api-im-zhuyh-gmail-com-91f4b9d-tmp
      outputs:
        parameters:
          - name: x_aa72edb
            valueFrom:
              path: /tmp/x_aa72edb.json
      container:
        image: "jinseob2kim/docker-rshiny"
        imagePullPolicy: Always
        volumeMounts:
        - name: workdir
          mountPath: /tmp/data
        command: ["/usr/bin/supervisord"]
      metadata:
        labels:
          app: naavre-visualizer-notebook