apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-viz
  labels:
    app: streamlit-viz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-viz
  template:
    metadata:
      labels:
        app: streamlit-viz
    spec:
      containers:
      - name: streamlit
        # 替换为您的镜像名称和标签
        image: xpsky/streamlit-viz:latest
        env:
        - name: API_BASE_URL
          value: "http://visualization-api"
        ports:
        - containerPort: 8501
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        # 可选：添加健康检查
        readinessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-viz
spec:
  selector:
    app: streamlit-viz
  ports:
  - port: 80
    targetPort: 8501
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streamlit-viz-ingress
  annotations:
    # 可选：添加 Ingress 注解，根据您的环境需要调整
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  rules:
  - host: viz.naavre.example.com  # 确保与API中STREAMLIT_URL环境变量一致
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: streamlit-viz
            port:
              number: 80