apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "visualization-api.fullname" . }}
  labels:
    {{- include "visualization-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "visualization-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "visualization-api.labels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      # ServiceAccount 和自动挂载 Token
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "visualization-api.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      {{- end }}

      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          # 环境变量
          env:
            # 自动注入 Pod 所在 Namespace
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            # 用户自定义 ENV
            {{- with .Values.env }}
            {{- range $key, $val := . }}
            - name: {{ $key }}
              value: {{ quote $val }}
            {{- end }}
            {{- end }}

          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP

          {{- with .Values.livenessProbe }}
          livenessProbe:
          {{ toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.readinessProbe }}
          readinessProbe:
          {{ toYaml . | nindent 12 }}
          {{- end }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          {{- if .Values.persistence.enabled }}
          volumeMounts:
            {{- with .Values.volumeMounts }}
            {{ toYaml . | nindent 12 }}
            {{- end }}
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}

      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "visualization-api.fullname" . }}-data
      {{- end }}

      {{- with .Values.volumes }}
      {{- if not .Values.persistence.enabled }}
      volumes:
      {{- end }}
      {{- toYaml . | nindent 6 }}
      {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}